---
- name: Install Docker, Nginx, and Git
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create directory for Docker keyring
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Set permissions for Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: "0644"
    - name: Add Docker repository
      block:
        - name: Get architecture
          command: dpkg --print-architecture
          register: architecture

        - name: Get OS codename
          command: . /etc/os-release && echo "$VERSION_CODENAME"
          register: os_codename

        - name: Add Docker repository to apt sources
          copy:
            content: |
              deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ os_codename.stdout }} stable
            dest: /etc/apt/sources.list.d/docker.list

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: true
    - name: Install Docker, Nginx, and Git
      apt:
        name:
          - git-all
          - nginx
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

- name: configure files to be served
  hosts: all
  become: true
  tasks:
    - name:
